/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.linkmanager;
import java.util.List;
import java.util.LinkedList;
import java.awt.*;
import javax.swing.JButton;
import java.net.URI;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Cukier
 */
public class LinkManagerUI extends javax.swing.JFrame {

    
    
    public LinkManagerUI() {
        initComponents();
        initmyComp();
        try{
            links=BazaDanych.getFromSQL();
            addlinkButtons();
            addfolderButtons();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "SQL Loading Issue.", "", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jPanel3.setBackground(new java.awt.Color(128, 128, 128));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(204, 102, 0));
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButton1.setMinimumSize(new java.awt.Dimension(1, 1));
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 102, 0));
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jButton2.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(150, 150, 150));
        jTextField1.setToolTipText("");
        jTextField1.setPreferredSize(new java.awt.Dimension(500, 30));

        jTextField2.setBackground(new java.awt.Color(150, 150, 150));
        jTextField2.setToolTipText("");
        jTextField2.setPreferredSize(new java.awt.Dimension(250, 30));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(64, 64, 64));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setMaximumSize(new java.awt.Dimension(745, 480));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(745, 480));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(128, 128, 128));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 451));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel2);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel4.setBackground(new java.awt.Color(128, 128, 128));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 451));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Name(optional):");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Adress:");

        jButton3.setBackground(new java.awt.Color(204, 102, 0));
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jButton3.setMinimumSize(new java.awt.Dimension(1, 1));
        jButton3.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("jLabel4");

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane1.setBackground(new java.awt.Color(64, 64, 64));
        jTextPane1.setBorder(null);
        jTextPane1.setForeground(new java.awt.Color(204, 204, 204));
        jTextPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String adr, name, direct;
        adr=jTextField1.getText();
        name=jTextField2.getText();
        if(adr.length()==0){
            return;
        }
        if(name.length()==0){
            try{
                name=TitleExtractor.getPageTitle(adr);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Can't get page title.", "", JOptionPane.ERROR_MESSAGE);
            }
        }
        direct=dir;
        if(links!=null){
        if(name.length()!=0&&validateHTTP_URI(adr)){
            try{
                Data newLink=new Data(BazaDanych.insertIntoSQL(adr, name, direct),name,adr,dir);
                links.add(newLink);
            }catch(Exception e){
                jTextField1.setText("");
                JOptionPane.showMessageDialog(null, "SQL Add Link Error.", "", JOptionPane.ERROR_MESSAGE);
                return;
            }
            addlinkButtons();
            jTextField1.setText("");
            jTextField2.setText("");
            return;
        }
        jTextField1.setText("");
        JOptionPane.showMessageDialog(null, "Wrong adress.", "", JOptionPane.ERROR_MESSAGE);
        return;
        }
        jTextField1.setText("");
        JOptionPane.showMessageDialog(null, "DB not downloaded.", "", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            links=BazaDanych.getFromSQL();
            addlinkButtons();
            addfolderButtons();
            jTextPane1.setText(dir);
            jTextPane1.setToolTipText(dir);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "SQL Download Error.", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(delt==0){
            delt=1;
            jLabel4.setText("Delete Mode ON");
        }else{
            delt=0;
            jLabel4.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
    
    public List<Data> links;
    private String dir;
    static private int delt;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private void addlinkButtons(){
        int y=15, count=0;
        int h=451;
        jPanel2.setPreferredSize(new Dimension(350,h));
        jPanel2.removeAll();
        for(int i=0;i<links.size();i++){
            if(links.get(i).direct.equals(dir)&&links.get(i).name.equals("")==false&&links.get(i).address.equals("")==false){
                count++;
                if(count>17){
                    h=h+25;
                    jPanel2.setPreferredSize(new Dimension(350,h));
                    jPanel2.setSize(new Dimension(350,h));
                }
                MyjButton b=new MyjButton(links.get(i).name);
                b.setBounds(15, y, 300, 20);
                b.setOpaque(false);
                b.setFocusPainted(false);
                b.setBorderPainted(false);
                b.setContentAreaFilled(false);
                try {
                    Image img1 = ImageIO.read(getClass().getResource("/my/linkbutt.png"));
                    Image img2 = ImageIO.read(getClass().getResource("/my/linkbuttmouse.png"));
                    Image img3 = ImageIO.read(getClass().getResource("/my/linkbuttpress.png"));
                    b.setIcon(new ImageIcon(img1));
                    b.setRolloverIcon(new ImageIcon(img2));
                    b.setPressedIcon(new ImageIcon(img3));
                  } catch (Exception ex) {
                      JOptionPane.showMessageDialog(null, "icon", "", JOptionPane.ERROR_MESSAGE);
                  }
                b.setHorizontalTextPosition(JButton.CENTER);
                b.setVerticalTextPosition(JButton.CENTER);
                b.adress=links.get(i).address;
                b.id=links.get(i).id;
                b.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        if(delt==0){
                            try{
                                URI adr=new URI(b.adress);
                                openWebpage(adr);
                            }catch(java.net.URISyntaxException e){
                            }
                        }else if(delt==1){
                            for(int j=0;j<links.size();j++){
                                if(links.get(j).id==b.id){
                                    try{
                                        BazaDanych.deleteFromSQL(b.id);
                                        links.remove(j);
                                        j--;
                                    }catch(Exception e){
                                        JOptionPane.showMessageDialog(null, "SQL Link Delete Error.", "", JOptionPane.ERROR_MESSAGE);
                                    }
                                }
                            }
                            addlinkButtons();
                        }

                    }
                });
                jPanel2.add(b,BorderLayout.CENTER);
                y=y+25;
            }    
        }
        jPanel2.repaint();
        
    }
    
    private void addfolderButtons(){
        jPanel4.removeAll();
        int y=15;
        int x=15;
        int count=1,h=451;
        jPanel4.setPreferredSize(new Dimension(350,h));
        jPanel4.setSize(new Dimension(350,h));
        String fName, lDir;
        int nline=0;
        if(dir.equals("/home/")==false){
            count++;
            JButton bt=new JButton("");
            bt.setBounds(x, y, 90, 90);
            bt.setOpaque(false);
            bt.setFocusPainted(false);
            bt.setBorderPainted(false);
            bt.setContentAreaFilled(false);
            try {
                Image img1 = ImageIO.read(getClass().getResource("/my/backfolder.png"));
                Image img2 = ImageIO.read(getClass().getResource("/my/backfolderchosen.png"));
                bt.setIcon(new ImageIcon(img1));
                bt.setRolloverIcon(new ImageIcon(img2));
                bt.setPressedIcon(new ImageIcon(img2));
              } catch (Exception ex) {
                  JOptionPane.showMessageDialog(null, "icon", "", JOptionPane.ERROR_MESSAGE);
              }
            bt.setHorizontalTextPosition(JButton.CENTER);
            bt.setVerticalTextPosition(JButton.CENTER);
            x=x+105;
            nline++;
            bt.addActionListener(new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                dir=dir.substring(0, dir.length()-1);
                                dir=dir.substring(0, dir.lastIndexOf("/")+1);
                                jTextPane1.setText(dir);
                                jTextPane1.setToolTipText(dir);
                                addfolderButtons();
                                addlinkButtons();
                        }
                    });
            jPanel4.add(bt,BorderLayout.CENTER);
        }
        List<String> fNames=new LinkedList();
        for(int i=0;i<links.size();i++){
            lDir=links.get(i).direct;
            if(lDir.length()>dir.length()&&lDir.substring(0, dir.length()).equals(dir)){
                fName=lDir.substring(dir.length(), lDir.length());
                try{
                fName=fName.substring(0, fName.indexOf("/"));
                }catch(Exception e){
                }
                if(fNames.contains(fName)==false){
                    count++;
                    
                    fNames.add(fName);
                    JButton bt=new JButton(fName);
                    bt.setName(fName);
                    bt.setBounds(x, y, 90, 90);
                    bt.setBorder(null);
                    bt.setOpaque(false);
                    bt.setFocusPainted(false);
                    bt.setBorderPainted(false);
                    bt.setContentAreaFilled(false);
                    try {
                        Image img1 = ImageIO.read(getClass().getResource("/my/folder.png"));
                        Image img2 = ImageIO.read(getClass().getResource("/my/openfolder1.png"));
                        bt.setIcon(new ImageIcon(img1));
                        bt.setRolloverIcon(new ImageIcon(img2));
                        bt.setPressedIcon(new ImageIcon(img2));
                      } catch (Exception ex) {
                          JOptionPane.showMessageDialog(null, "icon", "", JOptionPane.ERROR_MESSAGE);
                      }
                    bt.setHorizontalTextPosition(JButton.CENTER);
                    bt.setVerticalTextPosition(JButton.CENTER);
                    bt.addActionListener(new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                if(delt==0){
                                    String newdir;
                                    dir=dir+bt.getName()+"/";
                                    jTextPane1.setText(dir);
                                    jTextPane1.setToolTipText(dir);
                                    addfolderButtons();
                                    addlinkButtons();
                                }else if(delt==1){
                                    int aus=JOptionPane.showConfirmDialog(null, "Are you sure?", "", JOptionPane.YES_NO_OPTION);
                                    if(aus==JOptionPane.YES_OPTION){
                                        String fpath=dir+bt.getName()+"/";
                                        for(int j=0;j<links.size();j++){
                                            if(links.get(j).direct.contains(fpath)){
                                                try{
                                                    BazaDanych.deleteFromSQL(links.get(j).id);
                                                    links.remove(j);
                                                    j--;
                                                }catch(Exception e){
                                                    JOptionPane.showMessageDialog(null, "SQL Delete Folder Error.", "", JOptionPane.ERROR_MESSAGE);
                                                }
                                                
                                            }
                                        }
                                        addfolderButtons();
                                    }
                                }

                        }
                    });
                    jPanel4.add(bt,BorderLayout.CENTER);
                    nline++;
                    x=x+105;
                    if(nline==3){
                        nline=0;
                        x=15;
                        y=y+105;
                    }
                    if(count>11&&nline==0){
                        h=h+105;
                        jPanel4.setPreferredSize(new Dimension(350,h));
                        jPanel4.setSize(new Dimension(350,h));
                    }
                }
            }
        }
        
        JButton bt=new JButton("");
        bt.setBounds(x, y, 90, 90);
        bt.setOpaque(false);
        bt.setFocusPainted(false);
        bt.setBorderPainted(false);
        bt.setContentAreaFilled(false);
        try {
            Image img1 = ImageIO.read(getClass().getResource("/my/addfolder.png"));
            Image img2 = ImageIO.read(getClass().getResource("/my/addfolderchosen.png"));
            bt.setIcon(new ImageIcon(img1));
            bt.setRolloverIcon(new ImageIcon(img2));
            bt.setPressedIcon(new ImageIcon(img2));
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "icon", "", JOptionPane.ERROR_MESSAGE);
          }
        bt.setHorizontalTextPosition(JButton.CENTER);
        bt.setVerticalTextPosition(JButton.CENTER);
        bt.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                            String s = (String)JOptionPane.showInputDialog("New folder's name:");
                            if ((s != null) && (s.length() > 0)&&fNames.contains(s)==false) {
                                s=dir+s+"/";
                                try{
                                    Data newFold=new Data(BazaDanych.insertIntoSQL("", "", s),"","",s);
                                    links.add(newFold);
                                }catch(Exception e){
                                    JOptionPane.showMessageDialog(null, "SQL Add Folder Error.", "", JOptionPane.ERROR_MESSAGE);
                                }
                                addfolderButtons();
                            }
                    }
                });
        fNames.clear();
        jPanel4.add(bt,BorderLayout.CENTER);  
        jPanel4.repaint();
        
    }
    
    public static void openWebpage(URI uri) {
        Desktop desktop = Desktop.isDesktopSupported() ? Desktop.getDesktop() : null;
        if (desktop != null && desktop.isSupported(Desktop.Action.BROWSE)) {
                try{
                    desktop.browse(uri);
                }catch(Exception e){
                }
        }
    }
    
    public static boolean validateHTTP_URI(String uri) {
        final URL url;
        try {
            url = new URL(uri);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    
    private void initmyComp(){
        dir="/home/";
        jTextPane1.setText(dir);
        jTextPane1.setToolTipText(dir);
        jTextPane1.setEditable(false);
        delt=0;
        jLabel4.setText("");
        getContentPane().setBackground(new Color(32,32,32));
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.setFocusPainted(false);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        try {
            Image img1 = ImageIO.read(getClass().getResource("/my/syncicon.png"));
            Image img2 = ImageIO.read(getClass().getResource("/my/syncmouseicon.png"));
            Image img3 = ImageIO.read(getClass().getResource("/my/syncpressicon.png"));
            jButton1.setIcon(new ImageIcon(img1));
            jButton1.setRolloverIcon(new ImageIcon(img2));
            jButton1.setPressedIcon(new ImageIcon(img3));
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "icon", "", JOptionPane.ERROR_MESSAGE);
          }
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.setFocusPainted(false);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        try {
            Image img1 = ImageIO.read(getClass().getResource("/my/addlink.png"));
            Image img2 = ImageIO.read(getClass().getResource("/my/addlinkmouse.png"));
            Image img3 = ImageIO.read(getClass().getResource("/my/addlinkpress.png"));
            jButton2.setIcon(new ImageIcon(img1));
            jButton2.setRolloverIcon(new ImageIcon(img2));
            jButton2.setPressedIcon(new ImageIcon(img3));
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "icon", "", JOptionPane.ERROR_MESSAGE);
          }
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.setFocusPainted(false);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        try {
            Image img1 = ImageIO.read(getClass().getResource("/my/deleteicon.png"));
            Image img2 = ImageIO.read(getClass().getResource("/my/deletemouseicon.png"));
            Image img3 = ImageIO.read(getClass().getResource("/my/deletepressicon.png"));
            jButton3.setIcon(new ImageIcon(img1));
            jButton3.setRolloverIcon(new ImageIcon(img2));
            jButton3.setPressedIcon(new ImageIcon(img3));
          } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "icon", "", JOptionPane.ERROR_MESSAGE);
          }
    }
}

